bayke/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from baykeshop.public.sites import bayke_site


urlpatterns = [
    path('admin/', admin.site.urls),
    path('admins/', bayke_site.urls),
    path('', include('baykeshop.urls')),
    path('pages/', include('django.contrib.flatpages.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

module/user/urls.py
from django.urls import path
from baykeshop.module.user import views

urlpatterns = [
    path("login/", views.LoginView.as_view(), name="login"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("add/address/", views.BaykeShopAddressCreateView.as_view(), name="add_address"),
    
    path("address/", views.BaykeShopAddressListView.as_view(), name="addrs_list"),
    path("userinfo/", views.BaykeUserInfoTemplateView.as_view(), name="userinfo"),
    
    path("balance/", views.BaykeUserBalanceLogTemplateView.as_view(), name="balance"),
    path("browing/", views.browing, name="browing"),
]

module/user/models.py
#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@文件    :user.py
@说明    :拓展用户模型
@时间    :2023/02/19 17:11:31
@作者    :幸福关中&轻编程
@版本    :1.0
@微信    :baywanyun
'''


from django.db import models
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

from baykeshop.public.abstract import AbstractModel

User = get_user_model()


class BaykeUserInfo(AbstractModel):
    """ 一对一扩展的用户模型 """
    owner = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        verbose_name="用户"
    )
    avatar = models.ImageField("头像", upload_to="avatar/", max_length=200, blank=True, default="avatar/default.jpg")
    nickname = models.CharField(max_length=30, blank=True, default="", verbose_name="昵称")
    desc = models.CharField("描述", max_length=150, blank=True, default="")
    phone = models.CharField(
        max_length=11,
        blank=True,
        unique=True,
        null=True,
        verbose_name="手机号"
    )
    balance = models.DecimalField(
        "余额",
        max_digits=8,
        blank=True,
        decimal_places=2,
        default=0.00
    )

    class Meta:
        verbose_name = "用户"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.nickname or self.owner.username
    

class BaykeUserBalanceLog(AbstractModel):
    """ 用户余额变动表 """
    
    class BalanceChangeStatus(models.IntegerChoices):
        # 收支状态
        ADD = 1, _('增加')
        MINUS = 2, _('支出')
    
    class BalanceChangeWay(models.IntegerChoices):
        # 收支渠道或方式
        PAY = 1, _('线上充值')        
        ADMIN = 2, _('管理员手动更改') 
        SHOP = 3, _('余额抵扣商品')
    
    owner = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name="用户")
    amount = models.DecimalField("金额", max_digits=15, decimal_places=2)
    change_status = models.PositiveSmallIntegerField(
        choices=BalanceChangeStatus.choices, 
        blank=True,
        null=True
    )
    change_way = models.PositiveSmallIntegerField(
        choices=BalanceChangeWay.choices, 
        default=BalanceChangeWay.ADMIN        # 默认为后台
    )

    class Meta:
        verbose_name = '余额明细'
        verbose_name_plural = verbose_name

    def __str__(self):
        return f"{self.owner.username}-{self.amount}"


class BaykeShopAddress(AbstractModel):
    """ 收货地址 """
    owner = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")
    name = models.CharField("签收人", max_length=50)
    phone = models.CharField("手机号", max_length=11)
    email = models.EmailField("邮箱", blank=True, default="", max_length=50)
    province = models.CharField(max_length=150, verbose_name="省")
    city = models.CharField(max_length=150, verbose_name="市")
    county = models.CharField(max_length=150, verbose_name="区/县")
    address = models.CharField(max_length=150, verbose_name="详细地址")
    is_default = models.BooleanField(default=False, verbose_name="设为默认")
    
    class Meta:
        verbose_name = "收货地址"
        verbose_name_plural = verbose_name
       
    def __str__(self):
        return f'{self.name} {self.address}'

module/user/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import password_validation
from django.utils.functional import lazy
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from django.utils.html import format_html_join, format_html
from django.core.exceptions import ValidationError

from baykeshop.config.settings import bayke_settings
from baykeshop.models import BaykeUserInfo

User = get_user_model()

def _password_validators_help_text_html(password_validators=None):
    """
    Return an HTML string with all help texts of all configured validators
    in an <ul>.
    """
    help_texts = password_validation.password_validators_help_texts(password_validators)
    help_items = format_html_join('', '<p>{}</p>', ((help_text,) for help_text in help_texts))
    return format_html('<div class="help">{}</div>', help_items) if help_items else ''

password_validators_help_text_html = lazy(_password_validators_help_text_html, str)


class BaykeShopUsernameField(UsernameField):

    def widget_attrs(self, widget):
        return {
            'class': 'input',
            'placeholder':'请输入用户名...',
            **super().widget_attrs(widget)
        }
        
        
class LoginForm(AuthenticationForm):
    """ 登录表单 """
    username = UsernameField(
        widget=forms.TextInput(attrs={
            "autofocus": True, 
            "class": "input", 
            "placeholder":" 请输入用户名..."
        }))
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            "autocomplete": "current-password", 
            "class": "input", 
            "placeholder":" 请输入密码..."
        }),
    )


class RegisterForm(UserCreationForm):
    """ 注册用户表单 """
    password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password', 
            'class': 'input', 
            "placeholder":" 请输入密码..."
        }),
        help_text=password_validators_help_text_html(),
    )
    password2 = forms.CharField(
        label=_("Password confirmation"),
        widget=forms.PasswordInput(attrs={
            'autocomplete': 'new-password', 
            'class': 'input',
            "placeholder":" 请再次输入密码..."
        }),
        strip=False,
        help_text=_("Enter the same password as before, for verification."),
    )

    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': BaykeShopUsernameField}
        
        
class UserForm(forms.ModelForm):
    """ 用户信息表单 """
    class Meta:
        model = User
        fields = ['email',]


class UpdateUserInfoForm(forms.ModelForm):
    """ 用户关联信息表单 """
    class Meta:
        model = BaykeUserInfo
        fields = ['owner', 'avatar', 'phone', 'balance', 'nickname']
  
    def clean_phone(self):
        import re
        phone = self.cleaned_data['phone']
        reg = re.compile(bayke_settings.PHONE_REGX)
        if (phone is not None) and (not reg.search(phone)):
            raise ValidationError("手机号格式有误！")
        return phone

module/user/views.py
from django.shortcuts import render
from django.views.generic import FormView, CreateView, TemplateView, ListView
from django.contrib.auth import login
from django.contrib.auth import authenticate
from django.http.response import HttpResponseRedirect
from django.urls import reverse_lazy, reverse
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.views import (
    LoginView as BaseLoginView,
    LogoutView as BaseLogoutView
)

from baykeshop.config.settings import bayke_settings
from baykeshop.module.user.forms import LoginForm, RegisterForm, UserForm
from baykeshop.module.user.forms import UpdateUserInfoForm
from baykeshop.models import BaykeUserInfo, BaykeShopAddress, BaykeUserBalanceLog
from baykeshop.public.mixins import (
    JsonLoginRequiredMixin, JsonableResponseMixin, LoginRequiredMixin, JsonResponse
)


class LoginView(SuccessMessageMixin, BaseLoginView):
    """ 登录 """
    next_page = bayke_settings.NEXT_PAGE
    form_class = LoginForm
    redirect_field_name = 'redirect_to'
    template_name = "baykeshop/user/login.html"
    success_message = "%(username)s 登录成功！"

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            username=cleaned_data['username'],
        )
        

class LogoutView(BaseLogoutView):
    """ 登出 """
    template_name = 'baykeshop/user/logout.html'
    

class RegisterView(SuccessMessageMixin, FormView):
    """ 注册用户 """
    template_name = 'baykeshop/user/register.html'
    form_class = RegisterForm
    success_url = reverse_lazy("baykeshop:home")
    success_message = "%(username)s 注册成功，已登录！"
    
    def form_valid(self, form):
        if form.is_valid():
            new_user = form.save()
            auth_user = authenticate(username=new_user.username, 
                                     password=form.cleaned_data['password1'])
            BaykeUserInfo.objects.create(owner=auth_user, nickname=auth_user.username)
            login(self.request, auth_user)
        return super().form_valid(form)

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            username=cleaned_data['username'],
        )
        

class BaykeShopAddressCreateView(JsonLoginRequiredMixin, JsonableResponseMixin, CreateView):
    """ 添加地址 """
    model = BaykeShopAddress
    fields = ['name', 'phone', 'email', 'province', 'city', 'county', 'address', 'is_default']
    success_url = reverse_lazy('baykeshop:carts')
    
    def form_valid(self, form):
        form.instance.owner = self.request.user
        # 修改
        if self.request.POST.get('id') and self.request.POST.get('id').isdigit():
            # 查找默认的
            addr_default = BaykeShopAddress.objects.filter(owner=self.request.user, is_default=True)
            # 修改
            addr = BaykeShopAddress.objects.filter(id=int(self.request.POST.get('id')))
            addr.update(**form.cleaned_data)
            # 处理默认只能有一个
            if form.cleaned_data['is_default']:
                addr_default.exclude(id=addr.first().id).update(is_default=False)
            return JsonResponse({'code':'ok', 'message': '修改成功！'})
        
        # 新增 
        if form.cleaned_data['is_default']:
            BaykeShopAddress.objects.filter(owner=self.request.user, is_default=True).update(is_default=False)
        return super().form_valid(form)
    

class BaykeUserInfoTemplateView(LoginRequiredMixin, TemplateView):
    """ 个人中心 """
    
    template_name = "baykeshop/user/userinfo.html"
    
    def post(self, request, *args, **kwargs):
        userinfo, created = BaykeUserInfo.objects.get_or_create(
            owner=self.request.user,
            defaults={'owner': request.user}, 
        )
        
        user_form = UserForm(request.POST, instance=self.request.user)
        form = UpdateUserInfoForm(request.POST, request.FILES, instance=userinfo)

        if user_form.is_valid() and request.POST.get('email'):
            user_form.save()
            context = {'code': 'ok', 'message': '邮箱修改成功！' }
        elif user_form.errors:
            context = {'code': 'err', 'message': {**user_form.errors} }
            
        if form.is_valid() and request.POST.get('email') is None:
            form.save()
            context = {'code': 'ok', 'message': '修改成功！' }
        elif form.errors:
            context = {'code': 'err', 'message': {**form.errors} }
       
        return JsonResponse(context)
     
class BaykeUserBalanceLogTemplateView(LoginRequiredMixin, TemplateView):
    """ 余额记录 """
    template_name = "baykeshop/user/balance.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['qs'] = self.get_queryset()
        context['minus_balance'] = self.get_minus_balance()
        context['add_balance'] = self.get_add_balance()
        context['amount_minus'] = round((self.get_amount_minus()['amount__sum'] or 0), 2)
        context['amount_add'] = round(self.get_amount_add(), 2)
        return context
    
    def get_queryset(self):
        return BaykeUserBalanceLog.objects.filter(owner=self.request.user)
    
    def get_minus_balance(self):
        return self.get_queryset().filter(change_status=2)
    
    def get_add_balance(self):
        return self.get_queryset().filter(change_status=1)
    
    def get_amount_minus(self):
        # 累计支出
        from django.db.models import Sum
        return self.get_minus_balance().aggregate(Sum('amount'))
    
    def get_amount_add(self):
        # 累计充值
        try:
            self.request.user.baykeuserinfo.balance
        except BaykeUserInfo.DoesNotExist:
            BaykeUserInfo.objects.create(owner=self.request.user)
        amount_add = self.request.user.baykeuserinfo.balance + (self.get_amount_minus()['amount__sum'] or 0)
        return amount_add


class BaykeShopAddressListView(LoginRequiredMixin, ListView):
    """ 地址列表 """
    model = BaykeShopAddress
    template_name = "baykeshop/user/addr_list.html"
    context_object_name = "address_list"
    
    def get_queryset(self):
        return list(super().get_queryset().filter(owner=self.request.user).values(
            'id', 'name', 'phone', 'email', 'province', 'city', 'county', 'address', 'is_default'))
    
    def post(self, request, *args, **kwargs):
        # 删除地址
        code = ''
        message = ''
        addr_id = request.POST.get('addr_id')
        if addr_id:
            addr = BaykeShopAddress.objects.filter(id=int(addr_id))
            if addr.exists():
                addr.delete()     
                code = 'ok'
                message = '删除成功!'
            else:
                code = 'err'
                message = '该地址不存在！'
        else:
            code = 'err'
            message = '未传入有效参数！'
        return JsonResponse({'code': code, 'message': message})
    

def browing(request):
    from baykeshop.module.goods.models import BrowseHistory
    browsing_list = BrowseHistory.objects.filter(user_id=request.user.id).order_by('-add_date')[:10]
    history_data = []
    for item in browsing_list:
        spu = item.spu_id
        history_data.append({
            'id':spu.id,
            'title': spu.title,
            'description': spu.desc,
            'cover_pic_url': spu.cover_pic.url if spu.cover_pic else None})
    return render(request, 'baykeshop/user/browing.html', {'history': history_data})

templates/baykeshop/user/addr_list.html
{% extends 'baykeshop/user/userinfo.html' %}

{% load static %}

{% block title %}地址管理{% endblock %}


{% block extrastyle %}
<script src="{% static 'baykeshop/js/axios.min.js' %}"></script>
<script src="{% static 'baykeshop/js/request.js' %}"></script>
{% endblock %}
    

{% block userinfo_content %}
    {% include 'baykeshop/user/address_list.html' %}
{% endblock %}

templates/baykeshop/user/address.html
<style>
    .add-box{ border: solid 1px rgb(224, 224, 224); height: 150px;}
    .add-box:hover{border-color: rgb(251, 59, 59); transition: ease .5s;}
    .add-box .btn-default{position: absolute;top: 0;right: 0;}
    .active{border-color: rgb(251, 59, 59);}
</style>

<div class="box" id="address">
    {{ address_list|json_script:"addr-data" }}

    <h1 class="is-size-5">收货地址</h1>
    <img width="100%" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABLAAAAAECAYAAACeNca/AAAAAXNSR0IArs4c6QAAADhlWElmTU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAqACAAQAAAABAAAEsKADAAQAAAABAAAABAAAAAAdekyeAAABbUlEQVR4Ae2asW3DMBBFSWqGACkzRHprgyCbZASPEHiRjJC4TlYIkD4zWIyPd8WXzcZKw+KpkSCIBPHw+HWimNP5eHj5nae6vNv1pqPW4/fhfr5sW98e51TK9n5TPeanz6t+Ga+Thq9zwAd8cAL4oBzIB3zAB+qHRH0W04B6soHAB3xYvRj4fnMc5AP5sJoYrD8YjoHfF8XGNy2nvZ23Hqcy7bttS+7f7z7cubnUbnvGG6zg20DgAz4EAXxQEOQDPuCDEsAHpUE+4AM+KAF8UBrkAz7ggxLAB6UxQD4U272Sct7puG66Pq/O/bzefVy2aX//0z/6td1Xz19X/TJeJw1f54AP+OAE8EE5kA/4gA/UD/b3lPrMZgL1ZMsDfIhYxAd8CBUcBN+bxoF8CCnIB58WY9cPhd0r4esAq4kxktWJ3W2Bg914DQQ+4IMGBD7gAz4oAXxQGuQDPuCDEsAHpUE+4AM+KAF8UBqj58MfRyl5tp+pqv4AAAAASUVORK5CYII=">
    <div class="columns is-multiline mt-1">
        <div class="column is-3" v-for="addr in addressData" :key="addr.id">
            <div class="add-box is-clickable is-flex is-flex-direction-column is-align-items-start is-justify-content-center is-relative pl-5 pr-5"
                :class="{active: addr.is_default}"
                @click="pickAddress(addr)">
                <span class="tag is-danger btn-default is-radiusless" v-if="addr.is_default">{$ text $}</span>
                <h1 class="has-text-weight-bold">{$ addr.name $}</h1>
                <p>{$ addr.phone $}</p>
                <p>{$ addr.province $}{$ addr.city $}{$ addr.county $}{$ addr.address $}</p>
            </div>
        </div>
        <div class="column is-3">
            <div class="add-box is-clickable is-flex is-flex-direction-column is-align-items-center is-justify-content-center" 
                @click="openModal">
                <span class="icon is-size-1 has-text-grey-light"><i class="mdi mdi-plus"></i></span>
                <p class="mt-3 has-text-grey-light">添加新地址</p>
            </div>
        </div>
        
    </div>

    <b-modal
        v-model="isComponentModalActive"
        has-modal-card
        :can-cancel="false">
        <modal-form v-bind="formProps"></modal-form>
    </b-modal>

</div>
<script>
    const ModalForm = {
        props: ['id', 'name', 'phone', 'email', 'province', 'city', 'county', 'address', 'is_default'],
        data(){
            return {
                labelPosition: 'on-border',
                formProps: {
                    'id': this.id || null,
                    'name': this.name || "",
                    'phone': this.phone || "",
                    'email': this.email || "",
                    'province': this.province || "",
                    'city': this.city || "",
                    'county': this.county || "",
                    'address': this.address || "",
                    'is_default': this.is_default || false
                }
            }
        },
        template: `
            <div class="modal-card" style="min-width: 200px">
                <header class="modal-card-head">
                    <p class="modal-card-title">收货地址</p>
                </header>
                <section class="modal-card-body">
                    <b-field label="收件人" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.name"
                            type="text"
                            :value="formProps.name"
                            placeholder="Your name"
                            required>
                        </b-input>
                    </b-field>

                    <b-field label="手机号" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.phone"
                            type="text"
                            :value="formProps.phone"
                            placeholder="Your phone"
                            :hasCounter="false"
                            :maxlength="11"
                            pattern="[1][3,4,5,7,8,9][0-9]{9}"
                            validation-message="手机号格式有误！"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="省份" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.province"
                            type="text"
                            :value="formProps.province"
                            placeholder="Your province"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="城市" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.city"
                            type="text"
                            :value="formProps.city"
                            placeholder="Your city"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="区/县" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.county"
                            type="text"
                            :value="formProps.county"
                            placeholder="Your county"
                            required>
                        </b-input>
                    </b-field>
                    <b-field label="详细地址" :label-position="labelPosition">
                        <b-input
                            v-model="formProps.address"
                            type="text"
                            :value="formProps.address"
                            placeholder="Your address"
                            required>
                        </b-input>
                    </b-field>
                    <b-checkbox v-model="formProps.is_default" :value="formProps.is_default">设为默认</b-checkbox>
                </section>
                <footer class="modal-card-foot">
                    <b-button
                        label="取消"
                        @click="$parent.close()" />
                    <b-button
                        label="保存"
                        type="is-primary"
                        @click="save"/>
                </footer>
            </div>
        `,
        methods: {
            // 保存地址
            save(){
                // 数据库修改
                const sendData = new FormData()
                sendData.append('name', this.formProps.name)
                sendData.append('phone', this.formProps.phone)
                sendData.append('province', this.formProps.province)
                sendData.append('city', this.formProps.city)
                sendData.append('county', this.formProps.county)
                sendData.append('address', this.formProps.address)
                sendData.append('is_default', this.formProps.is_default)
                request({
                    method: 'post',
                    url: `{% url "baykeshop:add_address" %}`,
                    headers: {'Accept': 'application/json'},
                    data: sendData
                }).then(res => {
                    if (res.data.code == 'ok') {
                        navbar.toastMessage('is-success', res.data.message)
                        this.$parent.close()
                        location.reload()
                    }else{
                        navbar.toastMessage('is-danger', res.data.message)
                    }
                })
            },
        }
    }
</script>

<script>
    var addrs = JSON.parse(document.getElementById('addr-data').textContent);

    var address = new Vue({
        el: '#address',
        delimiters: ['{$', '$}'],
        components: {
            ModalForm
        },
        data: {
            addressData: addrs,
            text: "默认",
            isComponentModalActive: false,
            formProps: {
                'id': '',
                'name': '',
                'phone': '',
                'email': '',
                'province': '',
                'city': '',
                'county': '',
                'address': '',
                'is_default': false
            }
        },
        created(){
            // 选中默认地址
            this.addressData.forEach(element => {
                if (element.is_default){
                    this.formProps = element
                    this.text = "默认"
                }
            })
        },
        methods:{
            // 新增地址弹窗
            openModal(){
                this.isComponentModalActive = true
                this.formProps = {}
            },

            // 选择地址
            pickAddress(addr){
                this.formProps = addr
                this.addressData.forEach(element => {
                    if (this.formProps.id == element.id){
                        this.formProps.is_default = true
                        this.text = "选择 ✔"
                    }else{
                        element.is_default = false
                    }
                })
            },

        }
    })
</script>

templates/baykeshop/user/balance.html
{% extends 'baykeshop/user/userinfo.html' %}

{% block title %}
{{ request.user.username }} - 余额明细    
{% endblock %}

{% block userinfo_content %}
<div class="box is-radiusless">
    <h1 class=" is-size-4">我的余额</h1>
    <div class="dropdown-divider"></div>

    <div class="columns pl-6 pr-6 pt-3">
        <div class="column">
            <p class=" has-text-grey-light">账户可用余额</p>
            <h1 class="is-size-4">{{ request.user.baykeuserinfo.balance }}</h1> 
        </div>
        <div class="column">
            <p class=" has-text-grey-light">累计充值</p>
            <h1 class=" is-size-4">{{ amount_add }}</h1>
        </div>
        <div class="column">
            <p class=" has-text-grey-light">累计消费</p>
            <h1 class=" is-size-4">{{ amount_minus }}</h1>
        </div>
    </div>
    <div class=" dropdown-divider"></div>
    <div class="table-container pl-4 pr-4">
        <table class="table is-fullwidth is-hoverable">
            <tbody>
                {% for balance in qs %}
                <tr>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.get_change_status_display }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {% if balance.change_status == 1 %}  + {% else %} - {% endif %}{{ balance.amount }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.get_change_way_display }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.add_date }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>

    </div>

</div>

{% endblock %}

templates/baykeshop/user/browing.html
{% extends 'baykeshop/user/userinfo.html' %}

{% block title %}
{{ request.user.username }} - 余额明细    
{% endblock %}

{% block userinfo_content %}
<div class="box is-radiusless">
    <h1 class=" is-size-4">浏览记录</h1>
    <div class="dropdown-divider"></div>

    <table style="width:100%">
        {% for item in history %}
        <tr>
            <td>
                <p class=" has-text-grey-light">商品图</p>
                {% if item.cover_pic_url %}
                    <a href="{% url 'baykeshop:spu_detail' item.id %}"><img src="{{ item.cover_pic_url }}" alt="商品封面" style="width:50px;height:50px;"></a>
                {% endif %}
            </td>
            <td>
                <p class=" has-text-grey-light">商品标题</p>
                <h1 class=" is-size-4" style="font-size:18px !important;">{{ item.title|truncatechars:15 }}</h1>
            </td>
            <td>
                <p class=" has-text-grey-light">商品描述</p>
                <h1 class=" is-size-4" style="font-size:18px !important;">{{ item.description|truncatechars:15 }}</h1>
            </td>
        </tr>
        {% endfor %}
    </table>

    <div class=" dropdown-divider"></div>
    <div class="table-container pl-4 pr-4">
        <table class="table is-fullwidth is-hoverable">
            <tbody>
                {% for balance in qs %}
                <tr>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.get_change_status_display }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {% if balance.change_status == 1 %}  + {% else %} - {% endif %}{{ balance.amount }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.get_change_way_display }}
                    </td>
                    <td class="{% if balance.change_status == 1 %}  has-text-success-dark {% else %} has-text-danger-dark {% endif %}">
                        {{ balance.add_date }}
                    </td>
                </tr>
                {% endfor %}
            </tbody>

        </table>

    </div>

</div>

{% endblock %}

templates/baykeshop/user/email_form.html
<script>
    const EmailModalForm = {
        props: ['email'],
        delimiters: ['{$', '$}'],
        data(){
            return {
                formProps: {
                    email: this.email
                }
            }
        },
        created(){
            this.formProps.email = '{{ request.user.email }}'
        },
        methods:{
            save(){
                const sendData = new FormData()
                sendData.append('email', this.formProps.email)
                sendData.append('owner', '{{ request.user.id }}')
                request({
                    method: 'post',
                    url: `{% url "baykeshop:userinfo" %}`,
                    headers: {
                        'Accept': 'application/json',
                        'Content-Type': 'multipart/form-data'
                    },
                    data: sendData
                }).then(res => {
                    if (res.data.code == 'ok') {
                        navbar.toastMessage('is-success', res.data.message)
                        this.$parent.close()
                        location.reload()
                    }else{
                        navbar.toastMessage('is-danger', res.data.message)
                    }
                })
            }
        },
        template: `
        <div class="modal-card" style="width: auto">
            <header class="modal-card-head">
                <p class="modal-card-title">修改邮箱</p>
                <b-button class="delete" type="is-danger" @click="$parent.close()" />
            </header>
            <section class="modal-card-body" style="overflow:inherit;">
                <b-field label="Email">
                    <b-input type="email"
                        v-model="formProps.email"
                        value="formProps.email"
                        maxlength="30">
                    </b-input>
                </b-field>
            </section>
            <footer class="modal-card-foot">
                <b-button
                    label="取消"
                    @click="$parent.close()" />
                <b-button
                    label="确认"
                    @click="save"
                    type="is-primary" />
            </footer>
        </div>
        `
    }

</script>